import subprocess
import sys
import os
import shutil
import argparse
from pathlib import Path

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
AGNB_DIR = os.path.dirname(SCRIPT_DIR)
PROJECT_DIR = Path(AGNB_DIR).parent
SHARED_PROCESSED_DIR = PROJECT_DIR / "shared" / "assets" / "processed"
SHARED_SCRIPTS_DIR = PROJECT_DIR / "shared" / "scripts"
sys.path.insert(0, str(SHARED_SCRIPTS_DIR))

from image_manifest import (  # noqa: E402
    MANIFEST_FILENAME,
    included_entries,
    load_manifest,
    validate_asset_files,
)

MANIFEST_FILE = SHARED_PROCESSED_DIR / MANIFEST_FILENAME
ASM_IMAGES_FILE = Path(AGNB_DIR) / "src" / "asm" / "images.inc"
LOOSE_TARGET_DIR = Path(AGNB_DIR) / "tgt"


def selected_manifest_entries():
    entries = included_entries(load_manifest(MANIFEST_FILE))
    validate_asset_files(entries, SHARED_PROCESSED_DIR)
    return entries


def generate_images_include():
    entries = selected_manifest_entries()

    lines = [
        "; Generated by do_assembly.py\n\n",
        "image_type: equ 0\n",
        "image_width: equ image_type+3\n",
        "image_height: equ image_width+3\n",
        "image_filesize: equ image_height+3\n",
        "image_filename: equ image_filesize+3\n",
        "image_record_size: equ image_filename+3\n\n",
        f"num_images: equ {len(entries)}\n\n",
        "; bufferIds:\n",
    ]
    for entry in entries:
        lines.append(f"buf_{entry.name}: equ {entry.bufferId}\n")

    lines.append("\nimage_list: ; type; width; height; filesize; filename:\n")
    for entry in entries:
        lines.append(
            f"\tdl {entry.format}, {entry.width}, {entry.height}, "
            f"{entry.dataSize}, fn_{entry.name}\n"
        )

    lines.append("\n; files_list: ; filename:\n")
    for entry in entries:
        lines.append(f'fn_{entry.name}: db "images/{entry.rgba2}",0\n')

    ASM_IMAGES_FILE.write_text("".join(lines))
    print(f"Generated {ASM_IMAGES_FILE} from {len(entries)} manifest entries")


def copy_deployment(target_directory):
    target_directory = Path(target_directory)
    entries = selected_manifest_entries()
    rgba_files = [SHARED_PROCESSED_DIR / entry.rgba2 for entry in entries]

    if target_directory.exists():
        shutil.rmtree(target_directory)
    target_directory.parent.mkdir(parents=True, exist_ok=True)
    shutil.copytree(
        LOOSE_TARGET_DIR,
        target_directory,
        ignore=shutil.ignore_patterns("images"),
    )

    image_directory = target_directory / "images"
    image_directory.mkdir()
    for rgba_file in rgba_files:
        shutil.copy2(rgba_file, image_directory / rgba_file.name)

    print(
        f"Copied loose target and {len(rgba_files)} shared RGBA2222 files "
        f"to {target_directory}"
    )

def run_ez80asm():
    try:
        generate_images_include()
        # Store the current working directory
        original_dir = os.getcwd()

        # Define the directory containing the .asm file
        asm_directory = os.path.join(AGNB_DIR, "src", "asm")
        asm_file = "app.asm"
        output_file = os.path.join(AGNB_DIR, "tgt", "app.bin")
        output_asm_path = os.path.join("..", "..", "tgt", "app.bin")
        os.makedirs(os.path.dirname(output_file), exist_ok=True)

        # Change working directory to the directory containing the .asm file
        os.chdir(asm_directory)

        # Define the command with relative paths from the new working directory
        command = [
            "ez80asm",
            "-l",              # Option to generate listing file
            asm_file,          # Input assembly file
            output_asm_path    # Short path relative to the assembly directory
        ]

        # Execute the command
        result = subprocess.run(command, check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
        
        # Print the output
        print(result.stdout.decode())
        
    except subprocess.CalledProcessError as e:
        # ez80asm may report diagnostics on either output stream.
        if e.stdout:
            print(e.stdout.decode(), end="")
        if e.stderr:
            print(e.stderr.decode(), end="", file=sys.stderr)
        sys.exit(1)
    except Exception as e:
        # Handle other exceptions (e.g., if directory change fails)
        print(f"An error occurred: {e}")
        sys.exit(1)
    finally:
        # Restore the original working directory
        os.chdir(original_dir)

def copy_to_emulator():
    try:
        # Store the current working directory
        original_dir = os.getcwd()

        tgt_directory = os.path.join(
            AGNB_DIR, ".emulator", "sdcard", "mystuff", "agon-utils",
            "examples", "agnb", "images", "loose", "tgt",
        )

        # Change working directory to the original directory to ensure correct paths
        os.chdir(original_dir)

        copy_deployment(tgt_directory)

    except Exception as e:
        print(f"An error occurred while copying files: {e}")
        sys.exit(1)

def copy_to_sdcard():
    try:
        tgt_directory = "/media/smith/AGON/mystuff/agon-utils/examples/agnb/images/loose/tgt"
        copy_deployment(tgt_directory)

    except Exception as e:
        print(f"An error occurred while copying files: {e}")
        sys.exit(1)

def run_fab_agon_emulator():
    try:
        emulator_directory = os.path.join(AGNB_DIR, ".emulator")
        emulator_executable = os.path.join(
            emulator_directory, "fab-agon-emulator"
        )

        if not os.path.isfile(emulator_executable):
            raise FileNotFoundError(
                f"Emulator executable not found: {emulator_executable}"
            )

        process = subprocess.Popen(
            [emulator_executable],
            cwd=emulator_directory,
            stdin=subprocess.DEVNULL,
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
            start_new_session=True,
        )
        print(f"Launched fab-agon-emulator in background (PID {process.pid})")

    except Exception as e:
        print(f"An error occurred while launching the emulator: {e}")
        sys.exit(1)


def main():
    # Create an argument parser
    parser = argparse.ArgumentParser(description="Run assembly, copy, and emulator commands.")
    
    # Add optional switches for each function
    parser.add_argument('-a', action='store_true', help="Run ez80asm assembly")
    parser.add_argument('-c', action='store_true', help="Copy files to emulator")
    parser.add_argument('-e', action='store_true', help="Run fab-agon-emulator")
    parser.add_argument('-sd', action='store_true', help="Copy files to SD card")

    # Parse the arguments
    args = parser.parse_args()

    # If no options are given, run all functions
    if not args.a and not args.c and not args.e and not args.sd:
        run_ez80asm()
        copy_to_emulator()
        copy_to_sdcard()
        run_fab_agon_emulator()
    else:
        if args.a:
            run_ez80asm()
        if args.c:
            copy_to_emulator()
        if args.sd:
            copy_to_sdcard()
        if args.e:
            run_fab_agon_emulator()

if __name__ == "__main__":
    main()
