import subprocess
import sys
import os
import shutil
import argparse
from pathlib import Path

from PIL import Image

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
AGNB_DIR = os.path.dirname(SCRIPT_DIR)
PROJECT_DIR = Path(AGNB_DIR).parent
SHARED_PROCESSED_DIR = PROJECT_DIR / "shared" / "assets" / "processed"
ASM_IMAGES_FILE = Path(AGNB_DIR) / "src" / "asm" / "images.inc"
LOOSE_TARGET_DIR = Path(AGNB_DIR) / "tgt"
IMAGE_FORMAT = 1
FIRST_BUFFER_ID = 256


def generate_images_include():
    png_files = sorted(SHARED_PROCESSED_DIR.glob("*.png"))
    if not png_files:
        raise RuntimeError(
            f"No shared PNG files found in {SHARED_PROCESSED_DIR}; "
            "run shared/scripts/prepare_images.py first"
        )

    records = []
    for index, png_file in enumerate(png_files):
        rgba_file = png_file.with_suffix(".rgba2")
        if not rgba_file.is_file():
            raise FileNotFoundError(f"Missing shared RGBA2222 file: {rgba_file}")

        with Image.open(png_file) as image:
            width, height = image.size
        file_size = rgba_file.stat().st_size
        expected_size = width * height
        if file_size != expected_size:
            raise ValueError(
                f"RGBA2222 size mismatch for {rgba_file}: "
                f"expected {expected_size}, found {file_size}"
            )
        records.append(
            (png_file.stem, FIRST_BUFFER_ID + index, width, height, file_size)
        )

    lines = [
        "; Generated by do_assembly.py\n\n",
        "image_type: equ 0\n",
        "image_width: equ image_type+3\n",
        "image_height: equ image_width+3\n",
        "image_filesize: equ image_height+3\n",
        "image_filename: equ image_filesize+3\n",
        "image_record_size: equ image_filename+3\n\n",
        f"num_images: equ {len(records)}\n\n",
        "; buffer_ids:\n",
    ]
    for stem, buffer_id, _width, _height, _file_size in records:
        lines.append(f"buf_{stem}: equ {buffer_id}\n")

    lines.append("\nimage_list: ; type; width; height; filesize; filename:\n")
    for stem, _buffer_id, width, height, file_size in records:
        lines.append(
            f"\tdl {IMAGE_FORMAT}, {width}, {height}, {file_size}, fn_{stem}\n"
        )

    lines.append("\n; files_list: ; filename:\n")
    for stem, _buffer_id, _width, _height, _file_size in records:
        lines.append(f'fn_{stem}: db "images/{stem}.rgba2",0\n')

    ASM_IMAGES_FILE.write_text("".join(lines))
    print(f"Generated {ASM_IMAGES_FILE} from {len(records)} shared images")


def copy_deployment(target_directory):
    target_directory = Path(target_directory)
    rgba_files = sorted(SHARED_PROCESSED_DIR.glob("*.rgba2"))
    if not rgba_files:
        raise RuntimeError(
            f"No shared RGBA2222 files found in {SHARED_PROCESSED_DIR}; "
            "run shared/scripts/prepare_images.py first"
        )

    if target_directory.exists():
        shutil.rmtree(target_directory)
    target_directory.parent.mkdir(parents=True, exist_ok=True)
    shutil.copytree(
        LOOSE_TARGET_DIR,
        target_directory,
        ignore=shutil.ignore_patterns("images"),
    )

    image_directory = target_directory / "images"
    image_directory.mkdir()
    for rgba_file in rgba_files:
        shutil.copy2(rgba_file, image_directory / rgba_file.name)

    print(
        f"Copied loose target and {len(rgba_files)} shared RGBA2222 files "
        f"to {target_directory}"
    )

def run_ez80asm():
    try:
        generate_images_include()
        # Store the current working directory
        original_dir = os.getcwd()

        # Define the directory containing the .asm file
        asm_directory = os.path.join(AGNB_DIR, "src", "asm")
        asm_file = "app.asm"
        output_file = os.path.join(AGNB_DIR, "tgt", "app.bin")
        os.makedirs(os.path.dirname(output_file), exist_ok=True)

        # Change working directory to the directory containing the .asm file
        os.chdir(asm_directory)

        # Define the command with relative paths from the new working directory
        command = [
            "ez80asm",
            "-l",              # Option to generate listing file
            asm_file,          # Input assembly file
            output_file        # Output binary file (relative path from the new directory)
        ]

        # Execute the command
        result = subprocess.run(command, check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
        
        # Print the output
        print(result.stdout.decode())
        
    except subprocess.CalledProcessError as e:
        # Print the error message if the command fails
        print(f"Command failed with error: {e.stderr.decode()}")
        sys.exit(1)
    except Exception as e:
        # Handle other exceptions (e.g., if directory change fails)
        print(f"An error occurred: {e}")
        sys.exit(1)
    finally:
        # Restore the original working directory
        os.chdir(original_dir)

def copy_to_emulator():
    try:
        # Store the current working directory
        original_dir = os.getcwd()

        tgt_directory = os.path.join(
            AGNB_DIR, ".emulator", "sdcard", "mystuff", "agon-utils",
            "examples", "agnb", "loose", "tgt",
        )

        # Change working directory to the original directory to ensure correct paths
        os.chdir(original_dir)

        copy_deployment(tgt_directory)

    except Exception as e:
        print(f"An error occurred while copying files: {e}")
        sys.exit(1)

def copy_to_sdcard():
    try:
        tgt_directory = "/media/smith/AGON/mystuff/agon-utils/examples/agnb/loose/tgt"
        copy_deployment(tgt_directory)

    except Exception as e:
        print(f"An error occurred while copying files: {e}")
        sys.exit(1)

def run_fab_agon_emulator():
    try:
        emulator_directory = os.path.join(AGNB_DIR, ".emulator")
        emulator_executable = os.path.join(
            emulator_directory, "fab-agon-emulator"
        )

        if not os.path.isfile(emulator_executable):
            raise FileNotFoundError(
                f"Emulator executable not found: {emulator_executable}"
            )

        process = subprocess.Popen(
            [emulator_executable],
            cwd=emulator_directory,
            stdin=subprocess.DEVNULL,
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
            start_new_session=True,
        )
        print(f"Launched fab-agon-emulator in background (PID {process.pid})")

    except Exception as e:
        print(f"An error occurred while launching the emulator: {e}")
        sys.exit(1)


def main():
    # Create an argument parser
    parser = argparse.ArgumentParser(description="Run assembly, copy, and emulator commands.")
    
    # Add optional switches for each function
    parser.add_argument('-a', action='store_true', help="Run ez80asm assembly")
    parser.add_argument('-c', action='store_true', help="Copy files to emulator")
    parser.add_argument('-e', action='store_true', help="Run fab-agon-emulator")
    parser.add_argument('-sd', action='store_true', help="Copy files to SD card")

    # Parse the arguments
    args = parser.parse_args()

    # If no options are given, run all functions
    if not args.a and not args.c and not args.e and not args.sd:
        run_ez80asm()
        copy_to_emulator()
        copy_to_sdcard()
        run_fab_agon_emulator()
    else:
        if args.a:
            run_ez80asm()
        if args.c:
            copy_to_emulator()
        if args.sd:
            copy_to_sdcard()
        if args.e:
            run_fab_agon_emulator()

if __name__ == "__main__":
    main()
